import time
from random import randint


print("Protocol ANNOYING LOADING LOADING BECAUSE WHY NOT.")
time.sleep(1)

for i in range(3):
    print("L.")
    time.sleep(0.50)
    print("LO.")
    time.sleep(0.50)
    print("LOA.")
    time.sleep(0.50)
    print("LOAD.")
    time.sleep(0.50)
    print("LOADI.")
    time.sleep(0.50)
    print("LOADING.")
    time.sleep(0.50)
    print("LOADING..")
    time.sleep(0.50)
    print("LOADING...")
    time.sleep(0.50)

LOADING = input("Do you want to activate PRETTY loading screen? (N to skip loading) Y/N\n")

if LOADING == "Y":
    time.sleep(2.5)
    print("LOADING....")
    time.sleep(0.50)
    print("LOADING=======")
    time.sleep(0.50)
    print("=LOADING======")
    time.sleep(0.50)
    print("==LOADING=====")
    time.sleep(0.50)
    print("===LOADING====")
    time.sleep(0.50)
    print("====LOADING===")
    time.sleep(0.50)
    print("=====LOADING==")
    time.sleep(0.50)
    print("======LOADING=")
    time.sleep(0.50)
    print("=======LOADING")
    time.sleep(0.50)
    print("G=======LOADIN")
    time.sleep(0.50)
    print("NG=======LOADI")
    time.sleep(0.50)    
    print("ING=======LOAD")
    time.sleep(0.50)
    print("DING=======LOA")
    time.sleep(0.50)
    print("ADING=======LO")
    time.sleep(0.50)
    print("OADING=======L")
    time.sleep(0.50)
    print("LOADING=======")
    time.sleep(0.50)
    time.sleep(0.50)
    print("=LOADING======")
    time.sleep(0.50)
    print("==LOADING=====")
    time.sleep(0.50)
    print("===LOADING====")
    time.sleep(0.50)
    print("====LOADING===")
    time.sleep(0.50)
    print("=====LOADING==")
    time.sleep(0.50)
    print("======LOADING=")
    time.sleep(0.50)
    print("=======LOADING")
    print("Loading more loading protocols to load more loading.")
    time.sleep(3)

if LOADING == "N":

    time.sleep(2.5)
    print("LOADING....")
    time.sleep(0.50)
    print("=LOADING======")
    time.sleep(0.50)
    print("==LOADING=====")
    time.sleep(0.50)
    print("===LOADING====")
    time.sleep(0.50)
    print("====LOADING===")
    time.sleep(0.50)
    print("=====LOADING==")
    time.sleep(0.50)
    print("======LOADING=")
    time.sleep(0.50)
    print("=======LOADING")
    time.sleep(0.50)
    print("G=======LOADIN")
    time.sleep(0.50)
    print("NG=======LOADI")
    time.sleep(0.50)    
    print("ING=======LOAD")
    time.sleep(0.50)
    print("DING=======LOA")
    time.sleep(0.50)
    print("ADING=======LO")
    time.sleep(0.50)
    print("OADING=======L")
    time.sleep(0.50)
    print("LOADING=======")
    time.sleep(0.50)
    print("=LOADING======")
    time.sleep(0.50)
    print("==LOADING=====")
    time.sleep(0.50)
    print("===LOADING====")
    time.sleep(0.50)
    print("====LOADING===")
    time.sleep(0.50)
    print("=====LOADING==")
    time.sleep(0.50)
    print("======LOADING=")
    time.sleep(0.50)
    print("=======LOADING")
    print("Loading more loading protocols to load more loading.")
    time.sleep(3)

else:
    print("Sorry I dont speak stupid.")
    time.sleep(2.5)
    print("LOADING....")
    time.sleep(0.50)
    print("LOADING=======")
    time.sleep(0.50)
    print("=LOADING======")
    time.sleep(0.50)
    print("==LOADING=====")
    time.sleep(0.50)
    print("===LOADING====")
    time.sleep(0.50)
    print("====LOADING===")
    time.sleep(0.50)
    print("=====LOADING==")
    time.sleep(0.50)
    print("======LOADING=")
    time.sleep(0.50)
    print("=======LOADING")
    time.sleep(0.50)
    print("G=======LOADIN")
    time.sleep(0.50)
    print("NG=======LOADI")
    time.sleep(0.50)    
    print("ING=======LOAD")
    time.sleep(0.50)
    print("DING=======LOA")
    time.sleep(0.50)
    print("ADING=======LO")
    time.sleep(0.50)
    print("OADING=======L")
    time.sleep(0.50)
    print("LOADING=======")
    time.sleep(0.50)
    print("=LOADING======")
    time.sleep(0.50)
    print("==LOADING=====")
    time.sleep(0.50)
    print("===LOADING====")
    time.sleep(0.50)
    print("====LOADING===")
    time.sleep(0.50)
    print("=====LOADING==")
    time.sleep(0.50)
    print("======LOADING=")
    time.sleep(0.50)
    print("=======LOADING")
    print("Loading more loading protocols to load more loading.")
    time.sleep(3)

jokes = input("Would you like to hear our premium jokes for the best loading quality? Y/N\n")

if jokes == "Y":
    print("good.")
    
    random = randint(1,5)

    if random == 1:
        print("Why are elevator jokes so good?")
        time.sleep(3)
        print("Because they work on so many different levels.")
        time.sleep(3)
        print("Applause and laughter from the crowd of waiters.")
    if random == 2:
        print("I always used to get small shocks when touching metal objects, but it recently stopped.")
        time.sleep(3)
        print("Needless to say, I’m ex-static.")
        time.sleep(3)
        print("Applause and laughter from the crowd of waiters.")
    if random == 3:
        print("Why do Norwegians build their own tables?.")
        time.sleep(3)
        print("No Ikea!")
        time.sleep(3)
        print("Applause and laughter from the crowd of waiters.")
    if random == 4:
        print("Why did the coffee go to the police?")
        time.sleep(3)
        print("It got mugged.")
        time.sleep(3)
        print("Applause and laughter from the crowd of waiters.")    
    if random == 5:
        print("How many ears does Captain Kirk have?")
        time.sleep(3)
        print("Three: the left ear, the right ear, and the final frontier.")
        time.sleep(3)
        print("Applause and laughter from the crowd of waiters.")
    else:
        print("I can't hear you, joke coming up anyways dummy.")
        random = randint(1,5)

        if random == 1:
            print("Why   are elevator jokes so good?")
            time.sleep(3)
            print("Because they work on so many different levels.")
            time.sleep(3)
            print("Applause and laughter from the crowd of waiters.")
        if random == 2:
            print("I always used to get small shocks when touching metal objects, but it recently stopped.")
            time.sleep(3)
            print("Needless to say, I’m ex-static.")
            time.sleep(3)
            print("Applause and laughter from the crowd of waiters.")
        if random == 3:
            print("Why do Norwegians build their own tables?.")
            time.sleep(3)
            print("No Ikea!")
            time.sleep(3)
            print("Applause and laughter from the crowd of waiters.")
        if random == 4:
            print("Why did the coffee go to the police?")
            time.sleep(3)
            print("It got mugged.")
            time.sleep(3)
            print("Applause and laughter from the crowd of waiters.")    
        if random == 5:
            print("How many ears does Captain Kirk have?")
            time.sleep(3)
            print("Three: the left ear, the right ear, and the final frontier.")
            time.sleep(3)
            print("Applause and laughter from the crowd of waiters.")
    
if jokes == "N":
    print("bad. anyways its oppsite day")
    
    random = randint(1,5)

    if random == 1:
        print("Why are elevator jokes so good?")
        time.sleep(3)
        print("Because they work on so many different levels.")
        time.sleep(3)
        print("Applause and laughter from the crowd of waiters.")
    if random == 2:
        print("I always used to get small shocks when touching metal objects, but it recently stopped.")
        time.sleep(3)
        print("Needless to say, I’m ex-static.")
        time.sleep(3)
        print("Applause and laughter from the crowd of waiters.")
    if random == 3:
        print("Why do Norwegians build their own tables?.")
        time.sleep(3)
        print("No Ikea!")
        time.sleep(3)
        print("Applause and laughter from the crowd of waiters.")
    if random == 4:
        print("Why did the coffee go to the police?")
        time.sleep(3)
        print("It got mugged.")
        time.sleep(3)
        print("Applause and laughter from the crowd of waiters.")    
    if random == 5:
        print("How many ears does Captain Kirk have?")
        time.sleep(3)
        print("Three: the left ear, the right ear, and the final frontier.")
        time.sleep(3)
        print("Applause and laughter from the crowd of waiters.")

    else:
        print("I can't hear you, joke coming up anyways dummy.")
        random = randint(1,5)

        if random == 1:
            print("Why   are elevator jokes so good?")
            time.sleep(3)
            print("Because they work on so many different levels.")
            time.sleep(3)
            print("Applause and laughter from the crowd of waiters.")
        if random == 2:
            print("I always used to get small shocks when touching metal objects, but it recently stopped.")
            time.sleep(3)
            print("Needless to say, I’m ex-static.")
            time.sleep(3)
            print("Applause and laughter from the crowd of waiters.")
        if random == 3:
            print("Why do Norwegians build their own tables?.")
            time.sleep(3)
            print("No Ikea!")
            time.sleep(3)
            print("Applause and laughter from the crowd of waiters.")
        if random == 4:
            print("Why did the coffee go to the police?")
            time.sleep(3)
            print("It got mugged.")
            time.sleep(3)
            print("Applause and laughter from the crowd of waiters.")    
        if random == 5:
            print("How many ears does Captain Kirk have?")
            time.sleep(3)
            print("Three: the left ear, the right ear, and the final frontier.")
            time.sleep(3)
            print("Applause and laughter from the crowd of waiters.")
